### ISSUE TITLE
Invalidate user cookie if user is deleted/blocked

### ISSUE THREAD

**Issue by ternpixel** [factorio-tools/blueprints-database#3]
If I am logged in, and then delete my user account through arango, I can still navigate around to protected pages on the front end.

We should implement a proper method to ban/remove users and have their login invalidated

**Comment by teoxoy** [comment]
It happens automatically after 5min.
The token gets refreshed only every 5min.
We can lower it but I think 5min is fine.

**Comment by teoxoy** [comment]
This is also only relevant if we/the server changes the user data OR the user uses 2 or more machines and switches between them which is not that common imo.
