### ISSUE TITLE
[BUG] Trim whitespace from username during registration

### ISSUE THREAD

**Issue by richardsondev** [factorio-tools/blueprints-database#4]
**Describe the bug**
User account names can be registered with leading spaces and trailing spaces.

**To Reproduce**

1. Create a user account with a new similar to "test123"
2. Logout of the new account
3. Create a user account with the same name "test123"
4. Receive a 'username in use' error
5. Attempt to create a user account with the name "test123 " or " test123" (leading / trailing spaces)
6. Account is created successfully

**Expected behavior**
For both account names listed in step 5, we should receive a 'username in use' error

**Screenshots**
![image](https://user-images.githubusercontent.com/48865951/60489192-99a08600-9c58-11e9-8680-46b6c4f12b35.png)

**Comment by teoxoy** [comment]
We need to constrain the input to alphanumeric + `.-_` symbols (i.e. `[a-zA-Z0-9._-]`) so adding whitespace wouldn't be allowed anyway.

Do you think we should add any other symbols other than those mentioned above?

**Comment by ternpixel** [comment]
I can take care of this

**Comment by teoxoy** [comment]
It's just a matter of adding this decorator to the username field.
```js
@Matches(/^[a-zA-Z0-9._-]+$/, {
    message: 'username must contain only letters, numbers and the following symbols: ._-'
})
```

**Comment by ternpixel** [comment]
Great I’ll implement that. We will also want to allow more symbols than that (e.g. @ ) to ensure we accept any typical password. (My password uses a @ ;) )

**Comment by teoxoy** [comment]
That regex is only for the username not for other fields.
We shouldn't constrain passwords in the same fashion. I would like to add that password scoring lib and see how it plays out.

**Comment by ternpixel** [comment]
Ah yes, definitely.
